#include <iostream>
using namespace std;

int main()
{
	double numIndivMembers = 35.0;
	double numDualMembers = 150.0;
	double numFamMembers = 265.0;
	const double indivMembPrice = 99.0;
	const double dualMembPrice = 175.0;
	const double famMembPrice = 225.0;
	double indivMembRevenue = 0.0;
	double dualMembRevenue = 0.0;
	double famMembRevenue = 0.0;
	double totalMembRevenue = 0.0;
	double indivMembRevPercent = 0.0;
	double dualMembRevPercent = 0.0;
	double famMembRevPercent = 0.0;

	indivMembRevenue = numIndivMembers * indivMembPrice;
	dualMembRevenue = numDualMembers * dualMembPrice;
	famMembRevenue = numFamMembers * famMembPrice;

	totalMembRevenue = indivMembRevenue + dualMembRevenue + famMembRevenue;

	indivMembRevPercent = indivMembRevenue / totalMembRevenue * 100;
	dualMembRevPercent = dualMembRevenue / totalMembRevenue * 100;
	famMembRevPercent = famMembRevenue / totalMembRevenue * 100;

	cout << "The total amount of revenue generated by all memberships combined is $" << totalMembRevenue << endl;
	cout << "The individual membership generated $" << indivMembRevenue << " accounting for " << indivMembRevPercent << " percent of overall revenue" << endl;
	cout << "The dual membership generated $" << dualMembRevenue << " accounting for " << dualMembRevPercent << " percent of overall revenue" << endl;
	cout << "The family membership generated $" << famMembRevenue << " accounting for " << famMembRevPercent << " percent of overall revenue" << endl;



	system("pause");
	return 0;
}